const universitiesArray=[
  "Quaid-i-Azam University",
  "Allama Iqbal Open University",
  "International Islamic University, Islamabad",
  "National University of Sciences & Technology (NUST)",
  "COMSATS University Islamabad",
  "National University of Computer & Emerging Sciences (FAST-NU)",
  "Bahria University",
  "Air University",
  "Pakistan Institute of Engineering & Applied Sciences (PIEAS)",
  "Institute of Space Technology",
  "National University of Modern Languages (NUML)",
  "Federal Urdu University of Arts, Sciences & Technology",
  "Foundation University, Islamabad",
  "Capital University of Science & Technology (CUST)",
  "National Defence University",
  "Virtual University of Pakistan",
  "Shifa Tameer-e-Millat University",
  "Shaheed Zulfiqar Ali Bhutto Medical University",
  "Muslim Youth University",
  "National University of Technology",
  "Pakistan Institute of Development Economics",
  "National Skills University",
  "IBADAT International University",
  "Sir Syed CASE Institute of Technology",
  "Mohammad Ali Jinnah University (campus)",
  "National University of Medical Sciences (NUMS)"  ,
  "University of the Punjab, Lahore",
  "King Edward Medical University, Lahore",
  "University of Engineering & Technology, Lahore",
  "Forman Christian College (FCCU), Lahore",
  "National College of Arts, Lahore",
  "University of Veterinary & Animal Sciences, Lahore",
  "Punjab Tianjin University of Technology, Lahore",
  "Kinnaird College for Women, Lahore",
  "Government College University, Lahore",
  "Lahore College for Women University, Lahore",
  "University of Education, Lahore",
  "Bahauddin Zakariya University, Multan",
  "Islamia University of Bahawalpur, Bahawalpur",
  "University of Agriculture, Faisalabad",
  "Lahore University of Management Sciences (LUMS), Lahore",
  "National College of Business Administration & Economics, Lahore",
  "University of Central Punjab, Lahore",
  "University of Management & Technology, Lahore",
  "Virtual University of Pakistan, Lahore",
  "Allama Iqbal Open University (campus), Lahore",
  "Government College University, Faisalabad",
  "University of Sargodha, Sargodha",
  "National Textile University, Faisalabad",
  "Punjab University of Technology, Rasul Mandi Bahauddin",
  "University of Sahiwal, Sahiwal",
  "University of Okara, Okara",
  "University of Jhang, Jhang",
  "Ghazi University, Dera Ghazi Khan",
  "Mir Chakar Khan Rind University of Technology, D.G. Khan",
  "Ghazi National Institute of Engineering & Sciences, D.G. Khan",
  "University of Narowal, Narowal",
  "Al‑Qadir University, Sohawa",
  "Baba Guru Nanak University, Nankana Sahib",
  "University of Chakwal, Chakwal",
  "University of Mianwali, Mianwali",
  "Namal University, Mianwali",
  "Thal University, Bhakkar",
  "Kohsar University, Murree",
  "Institute of Management & Applied Sciences, Khanewal",
  "University of Layyah, Layyah",
  "University of Sargodha (duplicate entry removed)",
  "HITEC University, Taxila/Rawalpindi",
  "Hajvery University, Lahore",
  "Imperial College of Business Studies, Lahore",
  "Information Technology University, Lahore",
  "Institute of Arts & Culture, Lahore",
  "Institute of Management Sciences, Lahore",
  "Institute of Southern Punjab, Multan",
  "Khawaja Fareed University of Engineering & IT, Rahim Yar Khan",
  "Lahore Garrison University, Lahore",
  "Lahore Leads University, Lahore",
  "Lahore School of Economics, Lahore",
  "Minhaj University, Lahore",
  "Mir Chakar Khan Rind University of Tech, D.G. Khan",
  "Muhammad Nawaz Sharif University of Agriculture, Multan",
  "Muhammad Nawaz Sharif University of Engineering & Technology, Multan",
  "NFC Institute of Engineering & Technology, Multan",
  "Namal Institute, Mianwali",
  "Mishtar Medical University, Multan",
  "Nur International University, Lahore",
  "Pakistan Institute of Fashion & Design, Lahore",
  "Pir Mehr Ali Shah Arid Agriculture University, Rawalpindi",
  "Punjab Tianjin University of Technology, Lahore",
  "Qarshi University, Lahore",
  "Rawalpindi Medical University, Rawalpindi",
  "The Green International University, Lahore",
  "The Superior College, Lahore",
  "The University of Faisalabad, Faisalabad",
  "The Women University, Multan",
  "Times Institute, Multan",
  "University of Engineering & Technology, Taxila",
  "University of Gujrat, Gujrat",
  "University of Health Sciences, Lahore",
  "University of Lahore, Lahore",
  "University of South Asia, Lahore",
  "University of Wah, Wah",
  "Fatima Jinnah Women University, Rawalpindi",
  "Fatima Jinnah Medical University, Lahore",
  "Rawalpindi Women University, Rawalpindi",
  "University of Home Economics, Lahore",
  "University of Narowal",
  "University of Peshawar",
  "Islamia College University, Peshawar",
  "University of Agriculture, Peshawar",
  "University of Engineering & Technology, Peshawar",
  "Khyber Medical University",
  "Agricultural University, Dera Ismail Khan",
  "Gomal University",
  "Abbottabad University of Science & Technology",
  "Kohat University of Science & Technology",
  "Institute of Management Sciences, Peshawar",
  "University of Science & Technology, Bannu",
  "Abdul Wali Khan University Mardan",
  "Hazara University, Mansehra",
  "University of Swat",
  "University of Engineering & Applied Sciences, Swat",
  "University of Malakand",
  "University of Haripur",
  "Pak‑Austria Fachhochschule Institute of Applied Sciences and Technology, Haripur",
  "University of Engineering & Technology, Mardan",
  "Women University Mardan",
  "Bacha Khan University, Charsadda",
  "Northern University, Nowshera",
  "Qurtuba University of Science & Information Technology, Dera Ismail Khan",
  "Sarhad University of Science & Information Technology, Peshawar",
  "Gandhara University, Peshawar",
  "Abasyn University, Peshawar",
  "City University of Science & Information Technology, Peshawar",
  "CECOS University of Information Technology & Emerging Sciences, Peshawar",
  "Iqra National University, Swat",
  "University of Swabi",
  "Women University Swabi",
  "University of Buner",
  "University of Chitral",
  "University of Lakki Marwat",
  "Khushal Khan Khattak University, Karak",
  "FATA University, Kohat",
  "Aga Khan University, Karachi",
  "Baqai Medical University, Karachi",
  "Barrett Hodgson University, Karachi",
  "Benazir Bhutto Shaheed University Lyari, Karachi",
  "Benazir Bhutto Shaheed University of Technology & Skill Development, Khairpur Mirs",
  "COMMECS Institute of Business & Emerging Sciences, Karachi",
  "DHA Suffa University, Karachi",
  "Dow University of Health Sciences, Karachi",
  "Dadabhoy Institute of Higher Education, Karachi",
  "Dawood University of Engineering & Technology, Karachi",
  "Gambat Institute of Medical Sciences, Khairpur",
  "Greenwich University, Karachi",
  "Habib University, Karachi",
  "Hamdard University, Karachi",
  "Indus Valley School of Art & Architecture, Karachi",
  "Indus University, Karachi",
  "Institute of Business & Technology, Karachi",
  "Institute of Business Administration, Karachi",
  "Institute of Business Management (IoBM), Karachi",
  "Iqra University, Karachi",
  "Isra University, Hyderabad",
  "Jinnah Sindh Medical University, Karachi",
  "Jinnah University for Women, Karachi",
  "KASB Institute of Technology, Karachi",
  "Karachi Institute of Economics & Technology (KIET), Karachi",
  "Karachi School for Business & Leadership, Karachi",
  "Liaquat University of Medical & Health Sciences, Jamshoro",
  "Mehran University of Engineering & Technology, Jamshoro",
  "Mohammad Ali Jinnah University, Karachi",
  "NED University of Engineering & Technology, Karachi",
  "Nazeer Hussain University, Karachi",
  "Newport Institute of Communications & Economics, Karachi",
  "Pakistan Naval Academy, Karachi",
  "Peoples University of Medical & Health Sciences for Women, Nawabshah",
  "Preston Institute of Management, Science & Technology, Karachi",
  "Preston University, Karachi",
  "Quaid-e-Awam University of Engineering, Sciences & Technology, Nawabshah",
  "Shah Abdul Latif University, Khairpur",
  "Shaheed Benazir Bhutto City University, Karachi",
  "Shaheed Benazir Bhutto Dewan University, Karachi",
  "Shaheed Benazir Bhutto University of Veterinary & Animal Sciences, Nawabshah",
  "Shaheed Benazir Bhutto University, Shaheed Benazirabad",
  "Shaheed Mohtarma Benazir Bhutto Medical University, Larkana",
  "Shaheed Zulfikar Ali Bhutto Institute of Science & Technology (SZABIST), Karachi",
  "Shaheed Zulfiqar Ali Bhutto University of Law, Karachi",
  "Sindh Agriculture University, Tandojam",
  "Sindh Institute of Management & Technology, Karachi",
  "Sindh Institute of Medical Sciences, Karachi",
  "Sindh Madressatul Islam University, Karachi",
  "Sir Syed University of Engineering & Technology, Karachi",
  "Sukkur Institute of Business Administration, Sukkur",
  "Textile Institute of Pakistan, Karachi",
  "University of Karachi, Karachi",
  "University of Sindh, Jamshoro",
  "Zia-ud-Din University, Karachi",
  "University of Balochistan, Quetta",
  "Bolan University of Medical & Health Sciences, Quetta",
  "Al‑Hamd Islamic University, Quetta",
  "Balochistan University of Information Technology, Engineering & Management Sciences (BUITEMS), Quetta",
  "Sardar Bahadur Khan Women’s University, Quetta",
  "Balochistan University of Engineering & Technology, Khuzdar",
  "Lasbela University of Agriculture, Water & Marine Sciences, Uthal",
  "University of Turbat, Turbat",
  "University of Gwadar, Gwadar",
  "University of Makran, Panjgur",
  "University of Loralai, Loralai",
  "Mir Chakar Khan Rind University, Sibi",
  "University of Azad Jammu & Kashmir, Muzaffarabad",
  "Mirpur University of Science & Technology, Mirpur",
  "University of Poonch, Rawalakot",
  "University of Kotli, Kotli",
  "Women University of Azad Jammu & Kashmir, Bagh",
  "Mohi-ud-Din Islamic University, Nerian Sharif",
  "Azad Jammu & Kashmir University of Bhimber, Bhimber",
  "Karakoram International University, Gilgit",
  "University of Baltistan, Skardu",
"Others"]






export default universitiesArray